["```\r\npublic class MyChainedException {\r\n\r\n    public void main(String[] args) {\r\n        try {\r\n            throw new ArithmeticException(\"Top Level Exception.\")\r\n              .initCause(new IOException(\"IO cause.\"));\r\n        } catch(ArithmeticException ae) {\r\n            System.out.println(\"Caught : \" + ae);\r\n            System.out.println(\"Actual cause: \"+ ae.getCause());\r\n        }\r\n    }    \r\n}\r\n```","```\r\nCaught: java.lang.ArithmeticException: Top Level Exception.\r\nActual cause: java.io.IOException: IO cause.\r\n```","```\r\nclass NoLeaveGrantedException extends Exception {\r\n\r\n    public NoLeaveGrantedException(String message, Throwable cause) {\r\n        super(message, cause);\r\n    }\r\n\r\n    public NoLeaveGrantedException(String message) {\r\n        super(message);\r\n    }\r\n}\r\n\r\nclass TeamLeadUpsetException extends Exception {\r\n    // Both Constructors\r\n}\r\n```","```\r\npublic class MainClass {\r\n\r\n    public void main(String[] args) throws Exception {\r\n        getLeave();\r\n    }\r\n\r\n    void getLeave() throws NoLeaveGrantedException {\r\n        try {\r\n            howIsTeamLead();\r\n        } catch (TeamLeadUpsetException e) {\r\n            e.printStackTrace();\r\n            throw new NoLeaveGrantedException(\"Leave not sanctioned.\");\r\n        }\r\n    }\r\n\r\n    void howIsTeamLead() throws TeamLeadUpsetException {\r\n        throw new TeamLeadUpsetException(\"Team Lead Upset\");\r\n    }\r\n}\r\n```","```\r\ncom.baeldung.chainedexception.exceptions.TeamLeadUpsetException: \r\n  Team lead Upset\r\n    at com.baeldung.chainedexception.exceptions.MainClass\r\n      .howIsTeamLead(MainClass.java:46)\r\n    at com.baeldung.chainedexception.exceptions.MainClass\r\n      .getLeave(MainClass.java:34)\r\n    at com.baeldung.chainedexception.exceptions.MainClass\r\n      .main(MainClass.java:29)\r\nException in thread \"main\" com.baeldung.chainedexception.exceptions.\r\n  NoLeaveGrantedException: Leave not sanctioned.\r\n    at com.baeldung.chainedexception.exceptions.MainClass\r\n      .getLeave(MainClass.java:37)\r\n    at com.baeldung.chainedexception.exceptions.MainClass\r\n      .main(MainClass.java:29)\r\n```","```\r\npublic class MainClass {\r\n    public void main(String[] args) throws Exception {\r\n        getLeave();\r\n    }\r\n\r\n    public getLeave() throws NoLeaveGrantedException {\r\n        try {\r\n            howIsTeamLead();\r\n        } catch (TeamLeadUpsetException e) {\r\n             throw new NoLeaveGrantedException(\"Leave not sanctioned.\", e);\r\n        }\r\n    }\r\n\r\n    public void howIsTeamLead() throws TeamLeadUpsetException {\r\n        throw new TeamLeadUpsetException(\"Team lead Upset.\");\r\n    }\r\n}\r\n```","```\r\nException in thread \"main\" com.baeldung.chainedexception.exceptions\r\n  .NoLeaveGrantedException: Leave not sanctioned. \r\n    at com.baeldung.chainedexception.exceptions.MainClass\r\n      .getLeave(MainClass.java:36) \r\n    at com.baeldung.chainedexception.exceptions.MainClass\r\n      .main(MainClass.java:29) \r\nCaused by: com.baeldung.chainedexception.exceptions\r\n  .TeamLeadUpsetException: Team lead Upset.\r\n    at com.baeldung.chainedexception.exceptions.MainClass\r\n  .howIsTeamLead(MainClass.java:44) \r\n    at com.baeldung.chainedexception.exceptions.MainClass\r\n  .getLeave(MainClass.java:34) \r\n    ... 1 more\r\n```"]