["```\r\n@Test(expected = AssertionError.class)\r\npublic void whenError_thenIsNotCaughtByCatchException() {\r\n    try {\r\n        throw new AssertionError();\r\n    } catch (Exception e) {\r\n        Assert.fail(); // errors are not caught by catch exception\r\n    }\r\n}\r\n```","```\r\n@Test\r\npublic void whenError_thenIsCaughtByCatchError() {\r\n    try {\r\n        throw new AssertionError();\r\n    } catch (Error e) {\r\n        // caught! -> test pass\r\n    }\r\n}\r\n```"]